# Generated by Django 3.2 on 2021-04-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0007_feed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feed',
        ),
    ]
